steps:
- name: node:16.13.2
  entrypoint: npm
  args: ["install"]
  dir: "/vue_test"
- name: node:16.13.2
  entrypoint: npm
  args: ["run", "build"]
  dir: "/vue_test"
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: "/vue_test"
timeout: "1600s"